[package]
name = "step-p21"
description = "ISO 10303-21 (STEP file) parser and serde-based entity tables"
documentation = "https://docs.rs/step-p21"
keywords = ["step", "cad", "iso10303", "parser"]
categories = ["science", "parser-implementations"]
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
derive-new = { workspace = true }
derive_more = { workspace = true }
Inflector = { workspace = true }
itertools = { workspace = true }
nom = { workspace = true }
nom-language = { workspace = true }
serde = { workspace = true }
step-p21-derive = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
step-p11-derive = { workspace = true }
maplit = { workspace = true }
