[package]
name = "step-p21-derive"
description = "proc-macro support for step-p21"
documentation = "https://docs.rs/step-p21-derive"
keywords = ["step", "cad", "proc-macro"]
categories = ["science", "development-tools"]
readme = "../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
Inflector = { workspace = true }
proc-macro-crate = { workspace = true }
proc-macro-error2 = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
espr = { workspace = true }
insta = { workspace = true }
serde = { workspace = true }
step-p21 = { workspace = true }
trybuild = { workspace = true }
